// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlfunivfzodrpijtfppo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsZnVuaXZmem9kcnBpanRmcHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTI1NTIsImV4cCI6MjA2ODM4ODU1Mn0.9kMBD_qRtsTieO38e_i-qpgI3Tb8Zmq0iX2I0ftEdTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});